### ISSUE TITLE
login_veiw

### ISSUE THREAD

**Issue by PouryaMansouri** [PouryaMansouri/Laboratory#1]
- [x] get global login variable 
- [x] read all user information from pickle file from root_url (get from @PouryaMansouri code)
- [x] get username and password 
- [x] check input  
- [x] if valid change global login variable to True else False 
- [x] print result

**Comment by hamidrezafekri** [comment]
I can completely done according to issue

**Comment by PouryaMansouri** [comment]
Thanks, I close this issue.
please create new issue for refactor login function.
