### ISSUE TITLE
register_view

### ISSUE THREAD

**Issue by PouryaMansouri** [PouryaMansouri/Laboratory#2]
- [x] check  global login variable
- [x] let register if login== False
- [x] get patient all input
- [ ] check each input with validators that (@Ayazadeh @tahadavari ) write
- [ ] @tahadavari @Ayazadeh  you should witre validator for all feild in Patient and rewrite Patient class
- [x] check username that it's not duplicate
- [ ] create patients and print result
- [ ] add in pickle file
- [ ] return True
- [ ] write all exceptions that you nead

**Comment by hamidrezafekri** [comment]
here we have problem edit file should preform in file manager

**Comment by hamidrezafekri** [comment]
the second problem is related to return patient type but in base models init has no input so we can't make patient type

**Comment by hamidrezafekri** [comment]
I have done some of the Items in the list so I express the reason  why I can't finish it
